### ISSUE TITLE
Toffe dingen!

### ISSUE THREAD

**Issue by vasilisvg** [TimoVerkroost/minor-css-to-the-rescue#1]
Tof gebruik van border-radius in de chat!
Je rating is interactief! En met toffe animaties. Gaaf!
Nette CSS. Lekker bezig!

**Comment by TimoVerkroost** [comment]
Thanks, ben heel erg aan het experimenteren. En wil eigenlijk geen media queries gebruiken maar merk dat het eigenlijk wel nodig is in sommige gevallen.
