### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by vasilisvg** [TimoVerkroost/minor-css-to-the-rescue#2]
Het is nog niet echt responsive. Dingen gaan stuk op een kleiner scherm. Probeer eens van klein naar groot te werken.

**Comment by TimoVerkroost** [comment]
Ik moet toch media queries gebruiken denk ik. Al probeer ik dat niet te doen omdat ik ik wil leren deze zo min mogelijk of niet toe te passen.
