### ISSUE TITLE
# Form UX

### ISSUE THREAD

**Issue by vasilisvg** [TimoVerkroost/minor-css-to-the-rescue#3]
Er zijn een paar issues met de UX van je form:

- De vormgeving van de focus- en validatie-states is niet duidelijk: het contrast tussen de achtergrond en de kleur van de states is niet hoog genoeg.
- Focus states ontbreken helemaal op inputs en fieldset
- Button heeft wel een :hover maar geen :focus.

**Comment by TimoVerkroost** [comment]
Validation with :invalid and :focus fixed used other colors for contrast,
Added :focus states
Button has both :hover and :focus
