### ISSUE TITLE
Hee, tof!

### ISSUE THREAD

**Issue by vasilisvg** [TimoVerkroost/minor-css-to-the-rescue#8]
Dat ziet er goed uit man! Lekker bezig! Kijk hier nog even naar:

Kijk eens of je hier een *echte* site van kan maken. Lukt het je om alle elementen op een logische manier te tonen? Het mag op één pagina, maar ook op meerdere pagina's. Het onderwerp mag je natuurlijk zelf weten.

**Comment by TimoVerkroost** [comment]
Thx ga het proberen!
